AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

DB_PASSWORD = "SuperSecurePassword123!"

STRIPE_API_KEY = "sk_test_4eC39HqLyjWDarjtT1zdp7dc"

PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAu9FakeKeyData1234567890ABCDE
-----END RSA PRIVATE KEY-----"""
